sudo: required
group: edge
language: python
python:
  - "2.7"
env:
  global:
    - PATH="/usr/bin:$PATH"
services:
  - docker

install:
  - sudo pip install docker-py ansible
  - ansible --version
  # login docker
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"

script:
  - ansible-playbook playbook.yml --syntax-check
  - travis_wait 60 ansible-playbook playbook.yml
