---
- hosts: localhost
  connection: local
  vars:
    docker_organization: wizdevops
  pre_tasks:
    - name: install docker-py
      become: true
      become_method: sudo
      pip: 
        name: docker-py
        state: present
  tasks:
    - name: grab the vcs-url
      command: git config --get remote.origin.url
      register: vcs_url

    - name: grab the vcs-ref
      command: git rev-parse --short HEAD
      register: vcs_ref

    - name: build images and push to docker cloud
      docker_image:
        path: "{{ item.context }}"
        name: "{{ docker_organization }}/{{ item.image }}"
        tag: "{{ item.tag }}"
        state: present
        force: true
        nocache: false
        push: true
        rm: true
        buildargs:
          BUILD_DATE: "{{ ansible_date_time.iso8601 }}"
          VERSION: "{{ item.version }}"
          VCS_URL: "{{ vcs_url.stdout }}"
          VCS_REF: "{{ vcs_ref.stdout }}"
      with_items:
        - { context: ./base_alpine,
            image: "alpine",
            tag: latest,
            version: 1.0.2 }
        - { context: ./python/3,
            image: "python",
            tag: 3-alpine,
            version: 1.1.0 }
        - { context: ./python/2.7,
            image: "python",
            tag: 2.7-alpine,
            version: 1.1.1 }
        - { context: ./drupal/alpine,
            image: "drupal",
            tag: 8-alpine,
            version: 1.2.0 }
        - { context: ./drupal/debian,
            image: "drupal",
            tag: 8-debian,
            version: 1.0.0 }
        - { context: ./packer,
            image: "packer",
            tag: latest,
            version: 0.11.0 }
        - { context: ./java,
            image: "java",
            tag: 8-alpine,
            version: 1.0.1 }
        - { context: ./gocd/agent,
            image: "gocdagent",
            tag: latest,
            version: 16.11.0-4185 }
        - { context: ./gocd/server,
            image: "gocdserver",
            tag: latest,
            version: 16.11.0-4185 }
        - { context: ./monit,
            image: "monit",
            tag: latest,
            version: 1.0.0 }
        - { context: ./golang,
            image: "go",
            tag: latest,
            version: 1.7.3 }
        - { context: ./coffeescript,
            image: "coffeescript",
            tag: latest,
            version: 1.0.0 }
        - { context: ./alpine-mysql,
            image: "alpine-mysql",
            tag: latest,
            version: 1.0.0 }
        - { context: ./docker-webdav,
            image: "alpine-webdav",
            tag: latest,
            version: 1.0.0 }
